### ISSUE TITLE
Support constructors

### ISSUE THREAD

**Issue by latonz** [Cysharp/PrivateProxy#5]
Pretty much the title. It would be nice to have support for constructors. However, this may not fit the current extension method approach... but extern method could be exposed directly.

```c#
using PrivateProxy;

public class Sample
{
    private Sample(int x) {}
}

[GeneratePrivateProxy(typeof(Sample))]
partial struct SampleProxy;

// Generated
partial struct SampleProxy(Sample target)
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    public static extern Sample CreateSample(int x);
}
```

BTW thank you for this nice source generator!

**Comment by neuecc** [comment]
Okay, that suggestion sounds good!
