### ISSUE TITLE
Generics , static class and ref field support

### ISSUE THREAD

**Issue by Akeit0** [Cysharp/PrivateProxy#6]
I managed to reproduce something similar to this library in the Unity environment and managed to apply it to generics and static classes as well.
https://github.com/Akeit0/ILAttributes
I believe ref fields can also be applied by wrapping a ref into a ref struct.
However, since this is using IL Weaving, this is not as simple as it sounds.
Do you intend to introduce this or wait for formal support?

**Comment by neuecc** [comment]
PrivateProxy does not intend to do more than wrap the functionality provided by UnsafeAccessor.
So we will wait for UnsafeAccessor update.
